= TypeScript Cheat Sheet
:source-highlighter: coderay

Based on http://www.sitepen.com/blog/2013/12/31/typescript-cheat-sheet/[Sitepen's TypeScript Cheat Sheet]

.TypeScript cheatsheet
[cols="1,2a", options="header"]
|===
|1|2

2+|*Build script language*

|Any type (explicitly untyped) |`any`

|String  |`string`

|Number |`number`

|Boolean |`boolean`

2+|*Named types (interface, class, enum)*

|Interface
| 

[source, typescript]
----
interface IChild extends IParent, SomeClass {
  property:Type;
  optionalProp?:Type;
  optionalMethod?(arg1:Type):ReturnType;
}
----

|Class
|

[source,typescript]
----
class Child extends Parent implements IChild, IOtherChild {
  property:Type;
  defaultProperty:Type = 'default value';
  private _privateProperty:Type;
  static staticProperty:Type;
  constructor(arg1:Type) {
    super(arg1);
  }
  private _privateMethod():Type {}
  methodProperty:(arg1:Type) => ReturnType;
  overloadedMethod(arg1:Type):ReturnType;
  overloadedMethod(arg1:OtherType):ReturnType;
  overloadedMethod(arg1:CommonT):CommonReturnT {}
  static staticMethod():ReturnType {}
  subclassedMethod(arg1:Type):ReturnType {
    super.subclassedMethod(arg1);
  }
}
----

|Enum
|

[source, typescript]
----
enum Options {
  FIRST,
  EXPLICIT = 1,
  BOOLEAN = Options.FIRST \| Options.EXPLICIT
}
----


2+| *Object type literals* 

|Object with implicit Any properties | `{ foo; bar; }`

|Object with optional property   | `{ required:Type; optional?:Type; }`

|Hash map    | `{ [key:string]:Type; }`

2+| *Arrays*

| Array of strings    |`string[]` or `Array<string>`

| Array of functions that return strings  | `{ ():string; }[]` or `Array<() => string>`

2+| *Functions*

| Function
| 

[source, typescript]
----
{(arg1:Type, argN:Type):Type; } 

or 

(arg1:Type, argN:Type) => Type;
----

|Constructor | `{ new ():ConstructedType; }` or `new () => ConstructedType;`

|Function type with optional param | `(arg1:Type, optional?:Type) => ReturnType`

|Function type with rest param |`(arg1:Type, ...allOtherArgs:Type[]) => ReturnType`

|Function type with static property |  `{ ():Type; staticProp:Type; }`

|Default argument    |`function fn(arg1:Type = 'default'):ReturnType {}`

|Arrow function  
|

[source, typescript]
----
(arg1:Type):ReturnType => {} 

or 

(arg1:Type):ReturnType => Expression
----

2+| *Generics*

|Function using type parameters | `<T>(items:T[], callback:(item:T) => T):T[]`

|Interface with multiple types  |

[source, typescript]
----
interface Pair<T1, T2> {
  first:T1;
  second:T2;
}
----

|Constrained type parameter  | `<T extends ConstrainedType>():T`

2+| *Other*
| Type of a variable | `typeof varName`

|===